spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      # 最小空闲连接数
      minimum-idle: 2
      # 最大连接数
      maximum-pool-size: 4
      # 连接池名称
      pool-name: Mall-Hikari-Pool
      # 空闲超时时间 10m
      idle-timeout: 600000
      # 最大存活时间 1h
      max-lifetime: 3600000
      # 连接超时时间 1m
      connection-timeout: 60000
      # 连接测试查询sql
      connection-test-query: SELECT 1
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 3000ms

logging:
  level:
    root: info
    com.gaffey.mall: debug